name = "TinyJAMBU-DOM1-v1"
description = "TinyJAMBU with 1st order DPA protection"
author = ["Sammy Lin", "Abubakr Abdulgadir"]
url = "https://github.com/GMUCERG/TinyJAMBU-SCA"
license = "GPL-3.0"
version = "0.1.0"
[rtl]
sources = [
"src_rtl/design_pkg.vhd",
"src_rtl/LWC/NIST_LWAPI_pkg.vhd",
"src_rtl/tinyjambu_dp_ops.vhd",
"src_rtl/reg_n.vhd",
"src_rtl/dom_mul_reg.vhd",
"src_rtl/dom_mul.vhd",
"src_rtl/dom_mul_dep.vhd",
"src_rtl/dom_nlfsr_reg_feed.vhd",
"src_rtl/dom_nlfsr.vhd",
"src_rtl/tinyjambu_datapath.vhd",
"src_rtl/tinyjambu_control.vhd",
"src_rtl/CryptoCore.vhd",
"src_rtl/LWC/StepDownCountLd.vhd",
"src_rtl/LWC/key_piso.vhd",
"src_rtl/LWC/data_piso.vhd",
"src_rtl/LWC/PreProcessor.vhd",
"src_rtl/LWC/data_sipo.vhd",
"src_rtl/LWC/PostProcessor.vhd",
"src_rtl/LWC/fwft_fifo.vhd",
"src_rtl/LWC/LWC.vhd",
]
# includes = []
top = "LWC"
# clock.port = "clk"
# reset.port = "reset"
# reset.active_high = true
# reset.asynchronous = false
# "parameters"
[rtl.language]
vhdl.version = "2008"
vhdl.synopsys = true
# verilog.version = "2001"
# systemverilog.version = "2009"
# [tb]
# sources = ["LWC_TB_package.vhd", "LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_TB"
# [tb.language]
# vhdl.version = "1993"
# vhdl.synopsys = false
# verilog.version = "2001"
# systemverilog.version = "2009"
[lwc]
algorithm = "tinyjambu128"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
pt_block_bits = 32
ad_block_bits = 32
# [lwc.input_sequence]
# encrypt = [ "npub", "ad", "pt", "tag",]
# decrypt = [ "npub", "ad", "ct", "tag",]
# [lwc.hash]
# supported = false
# digest_bits = 128
[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 96
# sdi.bit_width = 32
sdi.num_shares = 2
[lwc.sca_protection]
target = ["timing", "sda", "dpa"]
order = 1
