[design]
name = "TinyJambu-DOM-2"
language.vhdl.standard = "2008"

[design.rtl]
sources = [
    ## LWC interface configuration:
    "src_rtl/NIST_LWAPI_pkg.vhd",
    ## CryptoCore interface configuration:
    "src_rtl/design_pkg.vhd",
    ## design sources:
    "src_rtl/tinyjambu_dp_ops.vhd",
    "src_rtl/reg_n.vhd",
    "src_rtl/dom_mul_reg.vhd",
    "src_rtl/dom_mul.vhd",
    "src_rtl/dom_mul_dep.vhd",
    "src_rtl/dom_nlfsr_reg_feed.vhd",
    "src_rtl/dom_nlfsr.vhd",
    "src_rtl/tinyjambu_datapath.vhd",
    "src_rtl/tinyjambu_control.vhd",
    "src_rtl/CryptoCore.vhd",
    ## LWC package:
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/fwft_fifo.vhd",
    ## SCA protected version of LWC top
    "src_rtl/LWC/LWC_SCA.vhd",
]
# includes = []
top = "LWC"
clock_port = "clk"
# reset.port = "reset"

[design.tb]
sources = ["src_tb/LWC_TB.vhd"]
top = "LWC_TB"
uut = "LWC"
[design.tb.generics]
G_FNAME_PDI = { file = "KAT/TinyJAMBU-DOM1-v1/pdi_shared.txt" }
G_FNAME_SDI = { file = "KAT/TinyJAMBU-DOM1-v1/sdi_shared.txt" }
G_FNAME_DO = { file = "KAT/TinyJAMBU-DOM1-v1/do.txt" }
