name: Main Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: gcc
    - run: ghdl --version
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade xeda
        python3 -m pip install --upgrade 'git+https://github.com/GMUCERG/LWC.git#egg=cryptotvgen&subdirectory=software/cryptotvgen'
    - name: verify
      run: |
        python3 ./test.py
    - name: benchmark
      run: |
        python3 ./benchmark.py ./TinyJAMBU-DOM1-v1.toml
